# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# ActiveMQ Artemis

FROM centos:7 as builder-env

LABEL maintainer="Apache ActiveMQ Team"

RUN yum groupinstall -y "Development Tools" && \
	yum install -y vim cmake glibc-devel.i686 \
		libgcc.i686 java-11-openjdk-devel && yum clean all

WORKDIR /opt
RUN curl https://downloads.apache.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz | tar -xz
RUN echo 'PATH=/opt/apache-maven-3.6.3/bin/:$PATH' >> ~/.bashrc

FROM builder-env as builder

ADD . /work

WORKDIR /work

VOLUME ["/work/target/lib"]
VOLUME ["/root/.m2/repository"]

WORKDIR /work

ENV PATH /opt/apache-maven-3.6.3/bin/:$PATH

CMD [ "bash", "-c", "/work/scripts/compile-native.sh"]
